ifeq ($(subdir),string)
sysdep_routines += memcpy_generic memcpy_thunderx memcpy_thunderx2 \
		   memcpy_falkor memmove_falkor memset_generic memset_falkor \
		   strlen_generic strlen_sve \
		   strcpy_generic strcpy_sve \
		   stpcpy_generic stpcpy_sve \
		   strcmp_generic strcmp_sve \
		   strchr_generic strchr_sve \
		   strchrnul_generic strchrnul_sve \
		   strnlen_generic strnlen_sve \
		   strncmp_generic strncmp_sve
endif
